#!/bin/bash

if [ -f /etc/lsb-release ]; then
  . /etc/lsb-release
  UBU_RELEASE=$DISTRIB_CODENAME
else
  UBU_RELEASE='trusty'
fi

function puppet_up {
echo "Setting up Puppetlabs repo."
echo "# Puppetlabs products
deb http://apt.puppetlabs.com ${UBU_RELEASE} PC1
" > /etc/apt/sources.list.d/puppetlabs.list

echo "Pinning puppet-agent to puppetlabs"
echo "Package: puppet-agent
Pin: origin "apt.puppetlabs.org"
Pin-Priority: 1000
" > /etc/apt/preferences.d/puppetlabs.pref

curl -s http://apt.puppetlabs.com/pubkey.gpg | apt-key add -
apt-get update
apt-get remove puppet-common -y
apt-get purge puppet-common -y
apt-get install puppet-agent=1.10.3-1${UBU_RELEASE} -y
ln -s /opt/puppetlabs/bin/facter /usr/local/bin/facter
ln -s /opt/puppetlabs/bin/puppet /usr/local/bin/puppet
}

echo "Setting up noexec /tmp..."
if [ -f /root/puppet_upgraded ]; then
  echo "Puppet already upgraded, skipping to next provisioner."
  exit 0
else
  echo "Disabling Chef client..."
  service chef-client stop
  update-rc.d chef-client disable
  echo "Running puppet..."
  puppet_up
  touch /root/puppet_upgraded
fi
